language: java
sudo: required
jdk:
  - openjdk11

branches:
  only:
    - master
    - develop


# Enable integration tests
before_script: 
  - curl -L https://github.com/jenkins-x/jx/releases/download/v2.0.1252/jx-linux-amd64.tar.gz | tar xzv "jx"
  - sudo chmod o+w .
  - sudo mv jx /usr/local/bin


script:
  - echo "Test"
  - jx step tag
  

    
