language: java
sudo: required
jdk:
  - openjdk11

branches:
  only:
    - master
    - develop


# Enable integration tests
before_script: 
  - echo $(bin/jx-release-version) > VERSION


script:
  - echo "Test"
  -  make bin/updatebot/push-version 
  

    
