language: java

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - master
    - develop

before_script:
  - echo MAVEN_OPTS=-Xmx1536m > ~/.mavenrc
  - sudo cp bin/jx-release-version /usr/bin/jx-release-version
  - sudo cp bin/updatebot /usr/bin/updatebot
  - echo $(jx-release-version) > VERSION

# Enable integration tests
script:
  - mvn clean install
  - mvn versions:set -DnewVersion=$(cat VERSION)"
  - mvn clean 
  - git add --all"
  - git commit -m "Release $(cat VERSION)" --allow-empty"
  - git tag -fa v$(cat VERSION) -m "Release version $(cat VERSION)"
  - git push origin v$(cat VERSION)"

  - mvn clean deploy -DskipTests

  
after_success:
  - export VERSION=`cat VERSION`|make updatebot/push-version 
