language: java
sudo: required
jdk:
  - openjdk11

branches:
  only:
    - master
    - develop


# Enable integration tests
before_script:
  - sudo cp bin/jx-release-version /usr/bin/jx-release-version
  - sudo cp bin/updatebot /usr/bin/updatebot
  - echo $(jx-release-version) > VERSION


script:
  - echo "Test"
  -  make updatebot/push-version 
  

    
